services:
    php:
        depends_on: [ database ]
        environment:
            APP_ENV: dev
            APP_DEBUG: true
            CADDY_SERVER_EXTRA_DIRECTIVES: 'tls /app/.infra/docker/tls/cert.pem /app/.infra/docker/tls/cert.key'
            SERVER_NAME: localhost:443
        command: [ 'frankenphp', 'run', '--config', '/etc/caddy/Caddyfile', '--watch' ]
        volumes:
            - '.:/app:rw'
            - './.infra/docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini:ro'

    scheduler:
        profiles: [ 'do-no-start' ]

    database:
        image: postgres:18-trixie
        volumes: [ 'database-data:/var/lib/postgresql' ]
        ports:
            -   target: 5432
                published: ${DATABASE_PORT:-5432}
                protocol: tcp
        healthcheck:
            test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
            timeout: 5s
            retries: 5
            start_period: 60s
        environment:
            - POSTGRES_DB=${DATABASE_DB:-electricity-prod}
            - POSTGRES_USER=${DATABASE_USER:-electricity-prod}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-electricity-prod}

volumes:
    database-data: ~
