services:
    php:
        ports:
            -   target: 80
                published: ${HTTP_PORT:-80}
                protocol: tcp
            -   target: 443
                published: ${HTTPS_PORT:-443}
                protocol: tcp
            -   target: 443
                published: ${HTTP3_PORT:-443}
                protocol: udp
        environment:
            APP_ENV: dev
            APP_DEBUG: true
            CADDY_SERVER_EXTRA_DIRECTIVES: 'tls /app/infra/docker/tls/cert.pem /app/infra/docker/tls/cert.key'
            SERVER_NAME: localhost:443
        command: [ 'frankenphp', 'run', '--config', '/etc/caddy/Caddyfile', '--watch' ]
        volumes:
            - '.:/app:rw'
            - './infra/docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini:ro'

    database:
        ports: [ '5432:5432' ]
